# General build settings
sudo: false
dist: trusty
language: node_js

env:
  - GIT_AUTHOR_NAME="Jason Yao"
  - GIT_AUTHOR_EMAIL="Hello@JasonYao.com"
  - GIT_COMMITTER_NAME="Jason Yao"
  - GIT_COMMITTER_EMAIL="Hello@JasonYao.com"

# Notification settings
notifications:
  email:
    recipients:
      - Hello@JasonYao.com
    # Only sends an email when the build status changes
    on_success: change
    on_failure: change

script:
  # Runs through the test suite
  - bin/test

## We only run the tests and deployment checks if the build succeeded
#after_success:
#  # Deployment steps (on success & on the correct branch)
#  - bin/deploy
#  branch:
#    - master
