# General build settings
sudo: false
dist: xenial
language: python

matrix:
  include:
    - python: 3.6
    # Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
    # See https://github.com/travis-ci/travis-ci/issues/9815 for more information
    - python: 3.7
      sudo: true

env:
  global:
    - GIT_AUTHOR_NAME="Jason Yao"
    - GIT_AUTHOR_EMAIL="Hello@JasonYao.com"
    - GIT_COMMITTER_NAME="Jason Yao"
    - GIT_COMMITTER_EMAIL="Hello@JasonYao.com"

# Notification settings
notifications:
  email:
    recipients:
      - Hello@JasonYao.com
    # Only sends an email when the build status changes
    on_success: change
    on_failure: change

before_script:
  - bin/install_dependencies

script:
  # Runs through the test suite
  - bin/lint
  - pip install -e .
  - pytest --pep8 --cov=pydotfiles tests/ --cov-fail-under=30 -m "not local"

after_success:
  - bin/generate-release

# We only do a release to pypi if the tests pass and we're on the master branch
deploy:
  provider: pypi
  user: "JasonYao"
  password:
    secure: 0g/tLWbYAb9JrqKds8qqFuYk55o9su4aSr27iKXEDVaCsiFWLKcanB3tgCE/TkM/M6+2CCJXWcxRqpwoUkGgkBKOus1nNDYymEo7TTpmGWMx93oJAU6XU1YK+z46EX8QbkmVIAA33qe7NeB9liDfXE0m1Od7t58kqbIjXxla37DRIxpdEQR/r8yhu8y6AydbxS5rL0qDASb3LunB/sJvfaPRfyPYG0tf/IYazGDFR+v2BPpSXYLOtToGop+3UtChH71K4v8F8K9xoVLGab856DbolUXgNN4jn8HdzRwShgLqNpoWY8lPLc6rY6ANf217zWvGJCcEudyCYAGasFFG22V4Almqsca5ltHDFH6nBqDlVtRhaNkeyU+6gh7jTW2h0HPOwQivh/oPz334RNft7RIoI+ydgWVtfoU9UmqNBmtxDCII+mWKRcBND68mXppCOIiBYbPJQmb9bT7k5oLvAnGqd9zuH30ZhGqHkxTPAmd7tZx791v46yT0bAXeS7jS7Tpg1k+TS/wfo6nrVz7+t1EI5HOkD9ptZiWGVORD+V7JPO53efazaVvG6H3U82QPTWVNg9SNaFdEUvUWBzPQlXKVvC5tio6hQc+obUYnxudXZJb7Sp5yVGouJzwskFn/3T9gxTMn6vtQZ8rc4gdqpyNBi65oudT5cIL9CVQ81I0=
  # We want both source code and binary releases
  distributions: "sdist bdist_wheel"

  # We want to use the existing build
  skip_cleanup: true

  # We want the ability to skip the deployment if it already exists
  skip_existing: true
  branch:
    - master
